version: "3"

services:
  backend:
    build:
      context: ./garde_backend
    command: gunicorn garde_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - django_app:/app

  frontend:
    build:
      context: ./garde_frontend
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
  django_app:
