version: "3"

services:
  backend:
    build:
      context: ./garde_backend
    # command: >
    #   sh -c "python manage.py migrate &&
    #         python manage.py loaddata pirogue/fixtures/countries_fixture.json &&
    #          gunicorn garde_backend.wsgi --bind 0.0.0.0:8000"
    command: "gunicorn garde_backend.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - backend_media:/app/media
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile

    ports:
      - "80:8080"
      - "81:8181"
      - "443:443"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

    depends_on:
      - backend
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw

  db:
    image: postgres:latest
    restart: unless-stopped

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=GARDE_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - pg_data:/var/lib/postgresql/data/:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  backend_media:
  pg_data:
    external: true
