services:
  backend:
    build:
      context: ./garde_backend
    command: gunicorn garde_backend.wsgi:application --bind 0.0.0.0:8001
    # command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - django_app:/app

  frontend:
    build:
      context: ./garde_frontend
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
  django_app:
# version: "3"

# services:
#   backend:
#     build:
#       context: ./garde_backend
#     command: >
#       sh -c "python manage.py migrate &&
#             python manage.py loaddata pirogue/fixtures/countries_fixture.json &&
#              gunicorn garde_backend.wsgi --bind 0.0.0.0:8000"
#     ports:
#       - "8000:8000"
#     volumes:
#       - backend_media:/app/media

#   frontend:
#     build:
#       context: ./garde_frontend
#     volumes:
#       - react_build:/react/build

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:8080"
#     volumes:
#       - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
#       - react_build:/var/www/react
#     depends_on:
#       - backend
#       - frontend

# volumes:
#   react_build:
#   backend_media:
