# Generated by Django 5.0.4 on 2024-05-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
