# Generated by Django 5.0.4 on 2024-04-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pirogue',
            old_name='lon',
            new_name='long',
        ),
    ]
