# Generated by Django 5.0.4 on 2024-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0003_alter_immigrant_created_by_alter_pirogue_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='immigrants/'),
        ),
    ]
