# Generated by Django 5.0.4 on 2024-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0005_remove_pirogue_number_pirogue_brand_pirogue_gps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirogue',
            name='material',
            field=models.CharField(blank=True, choices=[('wood', 'wood'), ('metal', 'metal'), ('plastic', 'plastic'), ('polyester', 'polyester')], max_length=100, null=True),
        ),
    ]
