# Generated by Django 5.0.4 on 2024-04-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0007_remove_immigrant_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immigrant',
            old_name='first_name',
            new_name='name',
        ),
    ]
