# Generated by Django 5.0.4 on 2024-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0008_rename_first_name_immigrant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='etat',
            field=models.CharField(choices=[('alive', 'alive'), ('dead', 'dead'), ('sick_evacuation', 'sick_evacuation'), ('pregnant', 'pregnant')], default='alive', max_length=100),
        ),
    ]
