# Generated by Django 5.0.4 on 2024-04-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0009_immigrant_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='fuel',
            field=models.IntegerField(default=0),
        ),
    ]
