# Generated by Django 5.0.4 on 2024-04-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0010_pirogue_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
