# Generated by Django 5.0.4 on 2024-04-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0011_pirogue_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='port',
            field=models.CharField(choices=[('ndagou', 'ndagou'), ('nouadhibou', 'nouadhibou'), ('nouakchott', 'nouakchott'), ('tanit', 'tanit')], default='ndagou', max_length=100),
            preserve_default=False,
        ),
    ]
