# Generated by Django 5.0.4 on 2024-04-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0012_pirogue_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirogue',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='long',
            field=models.CharField(max_length=100),
        ),
    ]
