# Generated by Django 5.0.4 on 2024-04-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0014_pirogue_number_alter_pirogue_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrant',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immigrants_birth_country', to='pirogue.country'),
        ),
        migrations.AlterField(
            model_name='immigrant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immigrant',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immigrants_nationality_country', to='pirogue.country'),
        ),
        migrations.AlterField(
            model_name='immigrant',
            name='pirogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immigrants', to='pirogue.pirogue'),
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
