# Generated by Django 5.0.4 on 2024-05-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0016_pirogue_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='port',
            field=models.CharField(choices=[('ndagou', 'ndagou'), ('nouadhibou', 'nouadhibou'), ('nouakchott', 'nouakchott'), ('tanit', 'tanit'), ('unknown', '-')], max_length=100),
        ),
    ]
