# Generated by Django 5.0.4 on 2024-05-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0017_textmodel_alter_pirogue_lat_alter_pirogue_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='etat',
            field=models.CharField(choices=[('saisie', 'saisie'), ('casse', 'casse'), ('abandonnee', 'abandonnee')], default='saisie', max_length=100),
        ),
    ]
