# Generated by Django 5.0.4 on 2024-05-07 23:08

from django.db import migrations, models
from datetime import datetime

# all the immigrants should have this free_at date
def add_free_at(apps, schema_editor):
    free_at = datetime.now()
    all = apps.get_model('pirogue.Immigrant').objects.all()
    for i in all:
        i.free_at = free_at
        i.save()

    

class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0018_pirogue_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='free_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(add_free_at)
    ]
