# Generated by Django 5.0.4 on 2024-05-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0021_alter_pirogue_motor_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='ciriminal_record',
            field=models.CharField(blank=True, choices=[('killer', 'killer'), ('danger', 'danger'), ('thief', 'thief')], max_length=100, null=True),
        ),
    ]
