# Generated by Django 5.0.4 on 2024-05-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0022_immigrant_ciriminal_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immigrant',
            old_name='ciriminal_record',
            new_name='criminal_record',
        ),
    ]
