# Generated by Django 5.0.4 on 2024-05-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0023_rename_ciriminal_record_immigrant_criminal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='criminal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
