# Generated by Django 5.0.4 on 2024-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0024_immigrant_criminal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrant',
            name='criminal_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
