# Generated by Django 5.0.4 on 2024-05-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0026_alter_immigrant_criminal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='days_at_sea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
