# Generated by Django 5.0.4 on 2024-05-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0027_pirogue_days_at_sea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrant',
            name='criminal_record',
            field=models.CharField(choices=[('theft', 'theft'), ('homicide', 'homicide'), ('torture', 'torture'), ('human_trafficking', 'human_trafficking'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
