# Generated by Django 5.0.4 on 2024-05-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0028_alter_immigrant_criminal_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrant',
            name='criminal_record',
            field=models.CharField(choices=[('theft', 'theft'), ('homocide', 'homocide'), ('torture', 'torture'), ('human_trafficking', 'human_trafficking'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
