# Generated by Django 5.0.4 on 2024-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0029_alter_immigrant_criminal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='sejour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
