# Generated by Django 5.0.4 on 2024-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0030_pirogue_sejour'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
