# Generated by Django 5.0.4 on 2024-05-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0031_immigrant_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='sejour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
