# Generated by Django 5.0.4 on 2024-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0033_immigrant_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='situation',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
