# Generated by Django 5.0.4 on 2024-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0034_pirogue_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirogue',
            name='situation',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
