# Generated by Django 5.0.4 on 2024-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0035_alter_pirogue_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='pirogues/'),
        ),
        migrations.AddField(
            model_name='pirogue',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='pirogues/'),
        ),
    ]
