# Generated by Django 5.0.4 on 2024-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0036_pirogue_video2_pirogue_video3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogue',
            name='landing_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
