# Generated by Django 5.0.4 on 2025-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogue', '0037_pirogue_landing_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrant',
            name='cin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immigrant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
